[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "api"
  node_bundler = "esbuild"

[functions."orders-auto-clear"]
  schedule = "@hourly"

[[redirects]]
  from = "/orders"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/index.html"
  status = 200
