[functions]
  directory = "api"
  node_bundler = "esbuild"

[[redirects]]
  from = "/orders"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/index.html"
  status = 200
